#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Google Sheets Connector für Claude (Team-Einrichtung)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11
ENV_FILE="${ENV_FILE:-$HOME/claude-sheets-connector.env}"   # merkt sich nur Projekt-ID + E-Mail, nie Secrets

SERVER_URL="https://sheetsmcp.googleapis.com/mcp/v1"
REDIRECT_URI="https://claude.ai/api/mcp/auth_callback"
APP_NAME="Claude Google Sheets"
CLIENT_NAME="Claude"
CONNECTOR_NAME="Google Sheets"
SCOPES="https://www.googleapis.com/auth/spreadsheets
https://www.googleapis.com/auth/spreadsheets.readonly
https://www.googleapis.com/auth/drive.file
https://www.googleapis.com/auth/drive.readonly"

# clip "text" — legt Text in die Zwischenablage (macOS / Windows / Linux).
clip() {
  if   command -v pbcopy   >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  elif command -v clip     >/dev/null 2>&1; then printf '%s' "$1" | clip
  elif command -v xclip    >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  else warn "Zwischenablage nicht verfügbar — bitte abtippen:"; say "$1"; return; fi
  printf '  %s📋 in der Zwischenablage:%s %s\n' "$GREEN" "$RESET" "$1"
}

# have_gcloud — gcloud gefunden (auch gcloud.cmd unter Windows/Git Bash)?
have_gcloud() { command -v gcloud >/dev/null 2>&1 || command -v gcloud.cmd >/dev/null 2>&1; }
gc() { if command -v gcloud >/dev/null 2>&1; then gcloud "$@"; else gcloud.cmd "$@"; fi; }

banner_de() {
  _clear
  printf '\n%s%s  Google Sheets Connector für Claude — Einrichtung%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%s  %s Schritte, ca. 20 Minuten%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  say "Dieser Assistent öffnet jede Seite für dich, erledigt, was er selbst kann,"
  say "und legt dir jeden Wert, den du eintippen müsstest, in die Zwischenablage."
  say "Du machst nur: einfügen (Cmd+V / Strg+V), klicken, Enter."
  printf '\n'
  warn "Client-ID und Client-Secret kommen NIE in diesen Assistenten oder in eine Datei."
  say "Die kopierst du direkt von Google in deinen Passwort-Manager."
  printf '\n'
  note "Jederzeit mit Ctrl-C abbrechen und später neu starten — der Assistent merkt sich Projekt und E-Mail."
  pause "Bereit? Enter drücken."
}

banner_de

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vorbereitung — Google-Werkzeug (gcloud)"
say "Mit dem Google-Werkzeug 'gcloud' kann der Assistent Projekt und Schnittstellen selbst anlegen."
GCLOUD=0
if have_gcloud; then
  GCLOUD=1; printf '  %s✓ gcloud ist installiert%s\n' "$GREEN" "$RESET"
else
  warn "gcloud ist nicht installiert."
  if command -v brew >/dev/null 2>&1 && confirm "Jetzt per Homebrew installieren (dauert 2–3 Minuten)?"; then
    brew install --cask google-cloud-sdk && GCLOUD=1 || warn "Installation fehlgeschlagen."
    # shellcheck disable=SC1091
    { source "$(brew --prefix)/share/google-cloud-sdk/path.bash.inc" 2>/dev/null || true; }
    have_gcloud && GCLOUD=1
  fi
  if [[ "$GCLOUD" == 0 ]]; then
    say "Kein Problem — dann führt der Assistent dich durch die Google-Website (zwei Klicks mehr)."
  fi
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google-Anmeldung"
if [[ "$GCLOUD" == 1 ]]; then
  say "Es öffnet sich ein Browserfenster. Melde dich mit deinem ARBEITS-Google-Konto an und erlaube den Zugriff."
  pause "Enter, dann Anmeldung im Browser abschließen."
  gc auth login --brief >/dev/null 2>&1 || gc auth login
  SUPPORT_EMAIL=$(gc config get-value account 2>/dev/null || true)
  say "Angemeldet als: ${BOLD}${SUPPORT_EMAIL}${RESET}"
else
  ask SUPPORT_EMAIL "Deine Arbeits-E-Mail-Adresse (Google-Konto):"
fi
write_env SUPPORT_EMAIL "$SUPPORT_EMAIL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google-Cloud-Projekt anlegen"
PROJECT_ID=$(_existing PROJECT_ID || true)
if [[ -n "$PROJECT_ID" ]]; then
  say "Projekt aus dem letzten Lauf: ${BOLD}${PROJECT_ID}${RESET}"
elif [[ "$GCLOUD" == 1 ]]; then
  PROJECT_ID="claude-sheets-$(date +%y%m%d)-$RANDOM"
  say "Lege Projekt '$APP_NAME' an (ID: $PROJECT_ID) …"
  if gc projects create "$PROJECT_ID" --name="Claude Sheets" --quiet; then
    printf '  %s✓ Projekt angelegt%s\n' "$GREEN" "$RESET"
  else
    warn "Anlegen per gcloud hat nicht geklappt (fehlende Rechte?). Weiter über die Website:"
    open_url "https://console.cloud.google.com/projectcreate"
    clip "Claude Sheets"
    step "Feld 'Projektname': einfügen (Strg+V) → 'Erstellen' → Meldung oben rechts abwarten → 'Projekt auswählen'."
    step "Oben auf der Seite steht jetzt die Projekt-ID (z. B. claude-sheets-123456)."
    ask PROJECT_ID "Projekt-ID hier eintippen:"
  fi
else
  open_url "https://console.cloud.google.com/projectcreate"
  clip "Claude Sheets"
  step "Feld 'Projektname': einfügen (Strg+V) → 'Erstellen' → Meldung oben rechts abwarten → 'Projekt auswählen'."
  step "Oben auf der Seite steht jetzt die Projekt-ID (z. B. claude-sheets-123456)."
  ask PROJECT_ID "Projekt-ID hier eintippen:"
fi
write_env PROJECT_ID "$PROJECT_ID"
[[ "$GCLOUD" == 1 ]] && gc config set project "$PROJECT_ID" --quiet >/dev/null 2>&1 || true
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Zwei Google-Schnittstellen aktivieren"
if [[ "$GCLOUD" == 1 ]] && gc services enable sheets.googleapis.com sheetsmcp.googleapis.com --project "$PROJECT_ID" --quiet; then
  printf '  %s✓ Google Sheets API + Google Sheets MCP API sind aktiv%s\n' "$GREEN" "$RESET"
  gc services list --enabled --project "$PROJECT_ID" 2>/dev/null | grep -i sheets | sed 's/^/    /' || true
else
  say "Bitte auf jeder der zwei Seiten oben prüfen, dass das Projekt '$PROJECT_ID' gewählt ist, dann 'Aktivieren' klicken."
  open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=$PROJECT_ID"
  pause "Wenn der Knopf 'Verwalten' zeigt: Enter."
  open_url "https://console.cloud.google.com/apis/library/sheetsmcp.googleapis.com?project=$PROJECT_ID"
  pause "Wenn der Knopf 'Verwalten' zeigt: Enter."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Zustimmungsbildschirm (Google Auth Platform)"
open_url "https://console.cloud.google.com/auth/overview?project=$PROJECT_ID"
step "Klick 'Jetzt starten'."
clip "$APP_NAME"
step "Feld 'App-Name': einfügen (Strg+V)."
step "Feld 'Support-E-Mail für Nutzer': ${BOLD}${SUPPORT_EMAIL}${RESET} auswählen."
step "'Weiter' → Zielgruppe: ${BOLD}Intern${RESET} wählen (nur falls es 'Intern' nicht gibt: 'Extern')."
step "'Weiter' → Kontaktdaten: wieder ${SUPPORT_EMAIL} → 'Weiter' → Richtlinie zustimmen → 'Erstellen'."
say "Du solltest jetzt eine Übersichtsseite mit '$APP_NAME' und 'Zielgruppe: Intern' sehen."
pause "Wenn ja: Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Berechtigungen (Scopes) eintragen"
open_url "https://console.cloud.google.com/auth/scopes?project=$PROJECT_ID"
step "Klick 'Bereiche hinzufügen oder entfernen' (rechts öffnet sich eine Leiste)."
clip "$SCOPES"
step "In der Leiste ganz nach unten: Feld 'Bereiche manuell hinzufügen' → einfügen (Strg+V) — alle 4 Zeilen auf einmal."
step "'Zur Tabelle hinzufügen' → 'Aktualisieren' → unten auf der Seite 'Speichern'."
say "Die Tabelle zeigt danach 4 Bereiche (zwei davon unter 'Sensible Bereiche' — das ist richtig)."
pause "Wenn 4 Bereiche gespeichert sind: Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "OAuth-Client anlegen (hier entstehen ID + Secret)"
open_url "https://console.cloud.google.com/auth/clients/create?project=$PROJECT_ID"
step "Anwendungstyp: ${BOLD}Webanwendung${RESET}."
clip "$CLIENT_NAME"
step "Feld 'Name': einfügen (Strg+V)."
pause "Enter, sobald der Name drin ist — dann kommt der nächste Wert in die Zwischenablage."
clip "$REDIRECT_URI"
step "Unter 'Autorisierte Weiterleitungs-URIs': '+ URI hinzufügen' → einfügen (Strg+V) → 'Erstellen'."
printf '\n'
warn "Jetzt zeigt Google 'Client-ID' und 'Clientschlüssel' (Secret) — NUR JETZT vollständig."
step "Beide Werte direkt in deinen Passwort-Manager kopieren (Eintrag z. B. 'Claude Google Sheets')."
step "NICHT hier eingeben, nicht in einen Chat, nicht in eine Datei."
until confirm "Sind beide Werte im Passwort-Manager gespeichert?"; do
  warn "Bitte erst speichern — das Secret ist später nicht mehr vollständig sichtbar."
done

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Connector in der Claude-Organisation hinterlegen (Owner)"
open_url "https://claude.ai/settings"
step "Links im Menü: Bereich ${BOLD}Organisation${RESET} → ${BOLD}Connectors${RESET}."
say "Siehst du KEINEN Bereich 'Organisation'? Dann fehlt deinem Konto die Owner-Rolle:"
note "Dann macht der Primary Owner diesen einen Schritt — gib ihm die Werte unten und ID/Secret über den Passwort-Manager."
printf '\n'
step "'Hinzufügen' → 'Custom'."
clip "$CONNECTOR_NAME"
step "Feld 'Name': einfügen (Strg+V)."
pause "Enter, sobald der Name drin ist — dann kommt die Server-Adresse in die Zwischenablage."
clip "$SERVER_URL"
step "Feld 'Remote MCP server URL': einfügen (Strg+V)."
step "'Erweiterte Einstellungen' aufklappen → 'OAuth Client ID' und 'OAuth Client Secret' aus dem Passwort-Manager einfügen → 'Hinzufügen'."
say "'$CONNECTOR_NAME' erscheint jetzt in der Connector-Liste der Organisation."
if ! confirm "Steht '$CONNECTOR_NAME' in der Liste?"; then
  SKIPPED+=("Schritt 8 durch den Primary Owner: Custom Connector '$CONNECTOR_NAME', URL $SERVER_URL, Client-ID/Secret aus dem Passwort-Manager")
  warn "Notiert — der Primary Owner trägt den Connector ein. Danach bitte hier weitermachen."
  pause
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Dich selbst verbinden"
open_url "https://claude.ai/settings"
step "Menü ${BOLD}Connectors${RESET} (deine persönliche Liste, nicht 'Organisation') → '$CONNECTOR_NAME' → 'Verbinden'."
step "Mit dem Arbeits-Google-Konto anmelden → 'Zulassen'."
say "'$CONNECTOR_NAME' zeigt jetzt 'Verbunden'."
pause "Wenn ja: Enter."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Test: lesen und schreiben"
say "Es öffnet sich ein leeres Test-Sheet (nicht die Hub-Tabelle). Link aus der Adresszeile kopieren."
open_url "https://sheets.new"
pause "Enter, sobald du den Link des Test-Sheets kopiert hast."
say "Öffne Cowork → neuer Chat → '+' → Connectors → '$CONNECTOR_NAME' einschalten. Dann diesen Text schicken (Link ergänzen):"
TEST_PROMPT='Öffne dieses Google Sheet: <LINK> — lies mir die ersten Zeilen vor und schreibe „Test von Claude" in eine freie Zelle.'
clip "$TEST_PROMPT"
step "In Cowork einfügen (Strg+V), <LINK> durch deinen Sheet-Link ersetzen, abschicken."
if confirm "Steht 'Test von Claude' jetzt im Sheet?"; then
  printf '  %s✓ Connector funktioniert — lesen UND schreiben%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("Test fehlgeschlagen — an Federico eskalieren (Schritt 10, was Claude geantwortet hat)")
  warn "Kein Problem — der Abschluss listet das als offen; bitte an Federico melden."
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Team-Nachricht"
TEAM_MSG='Der Connector „Google Sheets" ist für alle freigeschaltet. Einmalig: claude.ai → Einstellungen → Connectors → Google Sheets → „Verbinden" → mit dem Arbeits-Google-Konto anmelden → „Zulassen".
Danach in Cowork über „+" → Connectors auswählbar. Dauer: unter einer Minute, nichts zu installieren.'
MSG_FILE="$HOME/Desktop/google-sheets-connector-teamnachricht.txt"
[[ -d "$HOME/Desktop" ]] || MSG_FILE="$PWD/google-sheets-connector-teamnachricht.txt"
printf '%s\n' "$TEAM_MSG" > "$MSG_FILE"
clip "$TEAM_MSG"
say "Die Nachricht liegt in der Zwischenablage und in: $MSG_FILE"
warn "Erst verschicken, wenn Angelo den Datenfluss freigegeben hat."
say "Jede Kollegin / jeder Kollege macht danach nur diesen einen Klick-Weg — keine Installation."
pause "Enter zum Abschluss."

finish
